/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    jvm
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven("https://m2.dv8tion.net/releases")
    maven("https://m2.chew.pro/releases")
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform(kotlinBom))
    // Use the Kotlin JDK 8 standard library.
    implementation(kotlinStdlibJdk8)
    // Use the Kotlin test library.
    testImplementation(kotlinTest)
    // Use the Kotlin JUnit integration.
    testImplementation(kotlinTestJunit)
    implementation(jda)
    implementation(jdaChewtils)
}

application {
    // Define the main class for the application.
    mainClass.set("com.solxana.discord.reminder.AppKt")
}

tasks.wrapper {
    gradleVersion = GRADLE_VERSION
}
