const val kotlinBom: String = "org.jetbrains.kotlin:kotlin-bom:${Versions.Dependency.KOTLIN}"
const val kotlinStdlibJdk8: String = "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
const val kotlinTest: String = "org.jetbrains.kotlin:kotlin-test"
const val kotlinTestJunit: String = "org.jetbrains.kotlin:kotlin-test-junit"
const val jda: String = "net.dv8tion:JDA:${Versions.Dependency.JDA}"
const val jdaChewtils: String = "pw.chew:jda-chewtils:${Versions.Dependency.JDA_CHEWTILS}"
